name: Auto Deploy to EasyPanel

on:
  push:
    branches:
      - main  # Solo deploya cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -X POST http://206.183.130.17:3000/api/deploy/aab2b5625c2f01b6491232333d778f9a6a3b4bf35618ae15
